repos:
  - repo: local
    hooks:
     - id: flake8
       name: flake8
       entry: flake8 .
       language: system
     - id: isort
       name: isort
       entry: isort .
       language: system
