version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"

  web:
    build: .
    command: >
      bash -c "
      python manage.py makemigrations && 
      python manage.py migrate &&
      python manage.py load_products data/goods.csv &&
      python manage.py create_superuser && 
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - static_value:/static/
      - media_value:/media/
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
  static_value:
  media_value:
