version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build: .
    command: >
      sh -c 'python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python manage.py load_products data/goods.csv &&
             python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      mynetwork:
        aliases:
          - application

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
