version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - static_value:/static/
      - media_value:/media/
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  db_data:
  static_value:
  media_value:
