version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - static_value:/static/
      - media_value:/media/
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    depends_on:
      - db

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
#      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
#      - static_value:app/kids_shop/static/
#      - media_value:app/kids_shop/media/

volumes:
  db_data:
  static_value:
  media_value:
