name: Check Code Style

on:
  push:
    branches:
      - main

jobs:
  PEP8_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff isort

    - name: Check code with ruff
      run: ruff check . --fix

    - name: Check import order with isort
      run: isort .

    - name: Create .env file
      run: |
        touch .env
        echo "DB_ENGINE=${{ secrets.DB_ENGINE }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_HOST_TEST=${{ secrets.DB_HOST_TEST }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env'

    - name: Check UnitTests
      run: |
        docker-compose run web python manage.py test

    - name: Finish
      run: echo "Code style checks passed"

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: PEP8_check
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lama_shop:latest
