name: Check Code Style

on:
  push:
    branches:
      - main

jobs:
  PEP8_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff isort

    - name: Check code with ruff
      run: ruff check . --fix

    - name: Check import order with isort
      run: isort .

    - name: Check UnitTests
      run: |
       touch .env
       echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
       echo DB_NAME=${{ secrets.DB_NAME }} >> .env
       echo DB_USER=${{ secrets.DB_USER }} >> .env
       echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
       echo DB_HOST=${{ secrets.DB_HOST }} >> .env
       echo DB_HOST_TEST=${{ secrets.DB_HOST_TEST }} >> .env
       echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
       docker-compose run web python manage.py test

      #  SECRET_KEY=django-insecure--n*k=k^euc4t_*2!=0n*fo1k%slbmzu)#o(a7qjz(c*cz8(&ly
      #  DB_ENGINE=django.db.backends.postgresql
      #  DB_NAME=kids_shop
      #  DB_TEST_NAME=kids_shop_test
      #  DB_USER=dmitry_tok
      #  DB_PASSWORD=postgres
      #  DB_HOST=db
      #  DB_HOST_TEST=test_db
      #  POSTGRES_USER=dmitry_tok
      #  POSTGRES_PASSWORD=postgres
      #  POSTGRES_DB=kids_shop
      #  FIRST_METHOD=GET
      #  SECOND_METHOD=OPTIONS
      #  THIRD_METHOD=PATCH
      #  FOURTH_METHOD=DELETE
      #  FIFTH_METHOD=POST
      #  SIXTH_METHOD=PUT
      #  SUPER_LOGIN=admin@admin.net
      #  SUPER_PASSWORD=admin



    - name: Finish
      run: echo "Code style checks passed"

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: PEP8_check
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lama_shop:latest
